GET http://localhost:8080/produtos

###
DELETE http://localhost:8080/produtos/1

###

POST http://localhost:8080/produtos
Content-Type: application/json

{
    "titulo": "braço",
    "descricao": "teste",
    "img": "asda.com",
    "preco": "1500"
}
###

PUT http://localhost:8080/produtos/2
Content-Type: application/json

{
    "titulo": "braço",
    "descricao": "teste",
    "img": "asda.com",
    "preco": "1500"
}
###
GET http://localhost:8080/produt/9